spring.application.name: dummy-svc
server.port: 0

info:
  app: ${spring.application.name}

# Actuator security
management.security.enabled: false
security.user:
  name: admin
  password: secret

eureka.instance:
    preferIpAddress: true
    statusPageUrlPath: ${management.contextPath:/}info
    healthCheckUrlPath: ${management.contextPath:/}health
    # To setup a custom id
    # instanceId: ${spring.application.name}-${random.uuid}
    # metadataMap.servicePath: ${nimbus.mapping:/data}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 30